### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by alete89** [mopplayer/lattepanda-mainline-4.11#1]
Hi, I'm a linux newbie, but I really wan't to get debian up and running on my Latte. It boots well but WiFi and SD card reader are not functional.
Does this repo and the steps provided work in debian too?

**Comment by mopplayer** [comment]
Yes, it had been tested with debian 8(jessie).
You could download the ISO from https://www.debian.org/distrib/
Select offline installation.
And then install the  4.11.0-rc8 package.
sudo dpkg -i (package)

P.S.
1. There is no intel firmware by default, you have to download from here:
http://packages.ubuntu.com/zh-tw/linux-firmware

2. To enable bluetooth:
sudo apt-get install bluetooth bluez-tools blueman bluez

And modify bluetooth.service:
ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap
After rebooting the lattepanda, you can start bluetooth Manager.

3. Audio control panel:
sudo apt-get install pavucontrol

Additional note:
Because legacy Jessie distribution, the pulseaudio driver version was low, you could download form here:
http://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=pulseaudio
You have to force-install (break package dependence).
dpkg -i -B (package)
dpkg -i (package)

- libdbus (force)
- libltdl (normal)
- liborc (normal)
- libpulse (normal)
- pulseaudio (normal)

link pulseaudio shared library:
cd /usr/lib/x86_64-linux-gnu/pulseaudio/
sudo ln -s libpulsecommon-8.0.so libpulsecommon-5.0.so

And then reboot LattePanda, all you have done.
Testing had been done for 4.12.0-rc1.

**Comment by alete89** [comment]
Awesome! I'll try and leave some feedback. Thank you very much!

**Comment by xulihang** [comment]
This kernel also solves the audio problem on wintel box w8 pro! But the rtl8723bs wifi adapter still not working
