### ISSUE TITLE
Error after running .deb on debian

### ISSUE THREAD

**Issue by alete89** [mopplayer/lattepanda-mainline-4.11#3]
Hi, I installed debian 8.8.0 from CD1, everything worked well. Then I:
-cloned this repo
-cd in, and cd into /package
-cat *.z files into merged.zip
-unzipped merged
-run sudo dpkg -i the .deb
-sudo shutdown -r now

 and I got this:
![img_20170516_192559849](https://cloud.githubusercontent.com/assets/4999277/26131272/69363e26-3a6f-11e7-8280-f8c01229fece.jpg)

any advice?

**Comment by mopplayer** [comment]
Hi, run sudo dpkg -i the .deb, it will regenerate the initramfs to take some time.
Check it was finished by installation. Retry it again.

**Comment by alete89** [comment]
> Hi, run sudo dpkg -i the .deb, it will regenerate the initramfs to take some time.
> Check it was finished by installation. Retry it again.

Thanks for your reply, but it didn't work.
- in grub, I selected the original kernel in order to boot.
- I run sudo dpkg -i the .deb (output in attachment)
![img_20170517_230432220](https://cloud.githubusercontent.com/assets/4999277/26185033/b48c8c5a-3b5e-11e7-96b6-e98dc9123aab.jpg)


but I get the same black screen than before.

**Comment by mopplayer** [comment]
Hi, retry manually it:
sudo update-initramfs -u

My output:
Selecting previously unselected package lattepanda-64-mainline.
(Reading database ... 94321 files and directories currently installed.)
Preparing to unpack lattepanda-64-mainline_4.11.0-rc8-1_amd64.deb ...
Unpacking lattepanda-64-mainline (4.11.0-rc8-1) ...
Setting up lattepanda-64-mainline (4.11.0-rc8-1) ...
update-initramfs: deferring update (trigger activated)
Generating grub configuration file ...
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-4.11.0-rc8-panda
Found initrd image: /boot/initrd.img-4.11.0-rc8-panda
Found linux image: /boot/vmlinuz-3.16.0-4-amd64
Found initrd image: /boot/initrd.img-3.16.0-4-amd64
Found Windows Boot Manager on /dev/mmcblk0p1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for EFI firmware configuration
done
Installing RTL8723BS bluetooth driver...
done.
You must reboot your computer for the changes to take effect.
Processing triggers for initramfs-tools (0.120+deb8u3) ...
update-initramfs: Generating /boot/initrd.img-4.11.0-rc8-panda

**Comment by alete89** [comment]
well, it worked. after running `sudo update-initramfs -u` 4.11.0-rc8-panda boots.
then I `sudo apt-get update`d and `sudo apt-get upgrade`d
shouldn't I have to have wifi and SDcard running by now? they aren't.

**Comment by mopplayer** [comment]
Did you change BIOS settings? It had been indicated by README.

BIOS:
South Bridge -> Chipset -> SCC Configuration
SCC SDIO Support -> PCI Mode
SCC SD Card Support -> PCI Mode

Both 4.11.0-rc8 and 4.12.0-rc1 worked properly.

Note: SD card must be inserted before booting.

**Comment by alete89** [comment]
yeap! both BIOS settings are allright. No wifi or SDcard though. maybe I'll reinstall and rerun everything. :s

**Comment by alete89** [comment]
Can you provide the link to debian ISO you used for your install?

**Comment by alete89** [comment]
well... I reinstalled , re-ran the new files for 4.12.0-rc1, everything went well. but after reboot I can't get SDcard and wifi to work :S . Both BIOS settings are ok.

**Comment by mopplayer** [comment]
Hi, please recheck BIOS and save your settings by selecting save and reset option.
My ISO is http://cdimage.debian.org/debian-cd/current/amd64/bt-dvd/debian-8.8.0-amd64-DVD-1.iso.torrent
file name: debian-8.8.0-amd64-DVD-1.iso
Because your problem is only about SDcard and Wifi, BIOS may be the issue.
You could restore default settings and reconfigure BIOS settings.

**Comment by alete89** [comment]
I'm still not getting WiFi and SD card running. I doble checked BIOS settings. any other ideas? I even tried reinstalling debian and then running the package.deb again.

**Comment by alete89** [comment]
is tehre ANY step needed after `sudo dpkg -i package.deb` and rebooting ?

**Comment by mopplayer** [comment]
There are no more steps are needed.
Is your LattePanda 4G/64G?
You may need to reflash and upgrade your BIOS, check this:
https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Bios
And select LattePanda v1.1 4G default bios-J.zip.

**Comment by alete89** [comment]
@mopplayer I already updated to that BIOS on my 64GB Latte.
Maybe I'll re-flash it.
Thanks! 

_Sent from my Motorola XT1095 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StaubiKa** [comment]
Hi mopplayer,
first thanks for all the effort you already spent to help others installing debian on the LP! Much appreciated!

Unfortunately I have the same issue as alete89.
I have the Lattepanda 4G+64GB from the initial release (kickstarter) and therefore still version Z8300.
I just updated the BIOS with the Version 1.0 (due to CPU Z8300) and followed all your steps incl. the PCI Mode settings in BIOS. Unfortunately BT & Wifi not working.
I used the iso you mentioned above and installed debian several times with different options selected:
- with online sources (apt-get) / with offline sources (DVD iso)
- with Debian desktop environment / Debian desktop environment + LXDE / without both
- always used SSH server and standard system utilities but unchecked print server

Downloaded your package with 
`wget https://github.com/mopplayer/lattepanda-mainline-4.11/raw/master/package/lattepanda-64-mainline_4.12.0-rc1-1_amd64.deb.partaa` until ...j to not have to git clone the whole repo
then:
`cat * > lattepanda-64-mainline_4.12.0-rc1-1_amd64.deb` and 
`sudo dpkg -i lattepanda-64-mainline_4.12.0-rc1-1_amd64.deb`
output:
`staubi@lattepanda:~/latte$ sudo dpkg -i lattepanda-64-mainline_4.12.0-rc1-1_amd64.deb
Vormals nicht ausgewähltes Paket lattepanda-64-mainline wird gewählt.
(Lese Datenbank ... 94193 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von lattepanda-64-mainline_4.12.0-rc1-1_amd64.deb ...
Entpacken von lattepanda-64-mainline (4.12.0-rc1-1) ...
lattepanda-64-mainline (4.12.0-rc1-1) wird eingerichtet ...
update-initramfs: deferring update (trigger activated)
Generating grub configuration file ...
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Linux-Abbild gefunden: /boot/vmlinuz-4.12.0-rc1-panda
initrd-Abbild gefunden: /boot/initrd.img-4.12.0-rc1-panda
Linux-Abbild gefunden: /boot/vmlinuz-3.16.0-4-amd64
initrd-Abbild gefunden: /boot/initrd.img-3.16.0-4-amd64
Adding boot menu entry for EFI firmware configuration
erledigt
Installing RTL8723BS bluetooth driver...
done.
You must reboot your computer for the changes to take effect.
Trigger für initramfs-tools (0.120+deb8u3) werden verarbeitet ...
update-initramfs: Generating /boot/initrd.img-4.12.0-rc1-panda
staubi@lattepanda:~/latte$`
Sorry it's German but everything ran through without any issue

During the boot I get the following error:
![image](https://cloud.githubusercontent.com/assets/22428396/26763876/d6f5689c-495b-11e7-9d65-86fca6b0b18d.png)
When running the command `systemctl status rtl8723bsbt.service` I get the following output:
![image](https://cloud.githubusercontent.com/assets/22428396/26763936/21e834fa-495d-11e7-93e2-a3e4b6bf1830.png)

Hope you have any idea how I could get Wifi & BT to work. Everything else looks fine (including touchscreen).

Many thanks,
Martin

**Comment by mopplayer** [comment]
Oh, I notice that your SOC is z8300...,But I have no z8300 device to test.
It may be a issue, because the BIOS will be different...
I will ask DFRobot to see if there a z8300 board to send.
If alete89 is also z8300 SOC, the problem will be here.

**Comment by StaubiKa** [comment]
@mopplayer you really think that this could be due to BIOS? By the way: when I started to follow your project I downloaded the latest debian test release which figuered out to be debian 9 (!) already. during install it mentioned that rtl8723 driver is missing and if I want to load it from external storage. maybe this could be another approach?! did you already check the debian 9 testing release? when I realized that it is debian 9 I stopped installation as I wanted to follow your guide step-by-step first.
Many thanks again for your kind support!!!

@alete89 do you have z8300 or z8350?
how to find out: https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Bios#how-to-figure-out-the-verison-of-your-lattepanda

**Comment by mopplayer** [comment]
@StaubiKa  and Dear all:
I had tested Debian 9, the Wifi and Bluetooth worked properly by checking dmesg.
So, it should be the BIOS problem, if I got a board from DFRobot, I would check deeply.

**Comment by StaubiKa** [comment]
Hi @mopplayer,

ok, many thanks! If I can help you out (e.g. by sending you the output of any console command, log file, what ever, ...) just let me know. But please keep in mind that I am more or less a Linux newbie with "dangerous half knowledge / smattering" and probably would need precise information what to type. Anyway I am more than happy to support you and the community.

On top I will double-check debian 9 as well on my end. Any need to patch debian 9 after install or did everything work out of the box? Which driver did you use for WIFI / BT during installation? Any link? 😄 
Maybe we can figure out working and non working combinations with z8300 and z8350. I bet this would be a nice achievement for the LP-community.

I already noted down all my installation steps (detailed) and would like to publish this in the lattepanda forum with reference to your github once everything is working. Just to enable other newbies like me to have a working debian on their LP without hardly any Linux know how. Let me know if this is fine for you. 😄 


Kind regards
Martin

**Comment by alete89** [comment]
Yes, I have z8300, thats te one that was first shipped through kickstarter.

**Comment by alete89** [comment]
I can even leave the Latte on and give you an user to login through ssh if you need to test something.

**Comment by StaubiKa** [comment]
Just tried to install debian 9 test. I used iso dvd with and without additional sources from internet during install as well as the netinst version. in all installations wifi is not working. i tried to install driver following this guide: [http://www.lattepanda.com/forum/viewtopic.php?f=6&t=58&start=90#p2327](http://www.lattepanda.com/forum/viewtopic.php?f=6&t=58&start=90#p2327) but again without success 😒 
dmesg output:
![image](https://user-images.githubusercontent.com/22428396/26854476-973b079a-4b16-11e7-8328-24b70ae719af.png)

no wifi adapter shows up in network settings of debian (lxde). anything i could have missed?

**Comment by alete89** [comment]
any progress on support for z8300 yet? 👼

**Comment by mopplayer** [comment]
Hi, I got a z8300 board from DFRobot, it would take some time...

**Comment by alete89** [comment]
That's very good news!Thank you.

**Comment by mopplayer** [comment]
Wifi works properly now, because it is used bcm43340 chip.
Bluetooth will take some time to debug (same as Intel Edison)...

**Comment by mopplayer** [comment]
Done. LattePanda had been connected with My HTC phone Bluetooth.

**Comment by StaubiKa** [comment]
Awesome!!!
Any chance to quickly provide some information?
Which debian did you use? 8/9? Online/offline installation? Any special settings during installation? Any patches for Wifi / Bluetooth or sound?
I'd love to check it out today and write a step by step guide in the LP forum (with credits to your post and effort).

Many thanks
Martin

**Comment by mopplayer** [comment]
Please be patient, I will check Debian 8 and 9, and release the DEB file and steps.
All Wifi/Bluetooth and audio worked properly on Ubuntu 16.04 by now.
The key idea was from the Windows10 bcm43340 driver configuration.
Thanks a lot for interesting.

**Comment by StaubiKa** [comment]
Hi mopplayer,

Sorry! Wasn't meant to put any pressure on you! I am more than happy that you are willing to support!
Just let me know if I can help in any way!

**Comment by mopplayer** [comment]
That's OK.

When I used my laptop (with recent Windows 10 update) to connect LattePanda bluetooth, I found a funny issue.

Windows had regarded LattePanda as a "Computer", but it would be a "Audio" device after pairing and connecting, and then music stop playing forever...

Stopping bluetooth would cause that bluetooth device disappeared from Windows, I needed to shut down my laptop to wake up the device...

However, anything is OK before recent Windows 10 update.

**Comment by StaubiKa** [comment]
Haha!
One of the reasons I want to switch to Debian... If not only driver support was always such a pain. Always was a big challenge for me as a Linux noob 😕

I'll double-check this Windows 10 BT issue once I have a clean Debian installation and give a feedback.

**Comment by mopplayer** [comment]
Release for Ubuntu 16.04 and Debian 8 (Jessie)

**Comment by StaubiKa** [comment]
Wooohoo!
I'll give it a try right away this evening! Many thanks mate 😊👍
